/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package event_frame;

import event_management_project.Admin;
import event_management_project.AdminMaintain;
import event_management_project.Customer;
import event_management_project.CustomerList;
import event_management_project.EngagementEvent;

import event_management_project.EventListMaintain;
import event_management_project.ForeignCustomer;
import event_management_project.HoludEvent;
import event_management_project.LocalCustomer;
import event_management_project.MarriageEvent;
import event_management_project.ReceptionEvent;

/**
 *
 * @author hp
 */
public class LoginREgistration extends javax.swing.JFrame {

    /**
     * Creates new form LoginREgistration
     */
    EventListMaintain eventList;
    AdminMaintain adminList;
    CustomerList customerList;
    public LoginREgistration() {
        initComponents();
        adminList = new AdminMaintain();
        customerList = new CustomerList();
        eventList = new EventListMaintain();
        HoludEvent e = new HoludEvent("HoludEvent",14000,12000,15000);
        eventList.add(e);
        eventList.add(new MarriageEvent("MarriageEvent",20000,15000,40000));
        eventList.add(new EngagementEvent("EngagementEvent",13000,10000,18000));
        eventList.add(new ReceptionEvent("ReceptionEvent",15000,20000,13000));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logId = new javax.swing.JTextField();
        customerLogInBtn = new javax.swing.JButton();
        logPassword = new javax.swing.JPasswordField();
        adminLogInBtn = new javax.swing.JButton();
        logMessage = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerRegbtn = new javax.swing.JButton();
        regId = new javax.swing.JTextField();
        regName = new javax.swing.JTextField();
        regPhone = new javax.swing.JTextField();
        regEmail = new javax.swing.JTextField();
        regType = new javax.swing.JTextField();
        regPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        adminRegbtn = new javax.swing.JButton();
        regMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(792, 581));
        setPreferredSize(new java.awt.Dimension(792, 581));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));
        jPanel8.setMinimumSize(new java.awt.Dimension(792, 560));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(792, 600));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("ID");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Password");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 108, 40));
        jPanel6.add(logId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, 50));

        customerLogInBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerLogInBtn.setText("Customer Login");
        customerLogInBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customerLogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerLogInBtnActionPerformed(evt);
            }
        });
        jPanel6.add(customerLogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, 46));

        logPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPasswordActionPerformed(evt);
            }
        });
        jPanel6.add(logPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 193, 47));

        adminLogInBtn.setBackground(new java.awt.Color(204, 204, 255));
        adminLogInBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminLogInBtn.setText("Admin Login");
        adminLogInBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminLogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInBtnActionPerformed(evt);
            }
        });
        jPanel6.add(adminLogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, 46));

        logMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logMessage.setForeground(new java.awt.Color(204, 0, 0));
        logMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logMessage.setToolTipText("");
        jPanel6.add(logMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 370, 50));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 400, 470));

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel1.setText("ID");
        jPanel7.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 97, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 134, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Phone number");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, 38));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, 97, 43));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("local/foreign");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 130, 35));

        customerRegbtn.setBackground(new java.awt.Color(204, 204, 255));
        customerRegbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerRegbtn.setText("Customer Registration");
        customerRegbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customerRegbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRegbtnActionPerformed(evt);
            }
        });
        jPanel7.add(customerRegbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 190, 50));

        regId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regIdActionPerformed(evt);
            }
        });
        jPanel7.add(regId, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 22, 162, 29));
        jPanel7.add(regName, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 69, 162, 32));
        jPanel7.add(regPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 112, 162, 40));

        regEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmailActionPerformed(evt);
            }
        });
        jPanel7.add(regEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 162, 38));
        jPanel7.add(regType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 162, 35));

        regPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPasswordActionPerformed(evt);
            }
        });
        jPanel7.add(regPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 162, 36));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 88, 34));

        adminRegbtn.setBackground(new java.awt.Color(204, 204, 255));
        adminRegbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminRegbtn.setText("Admin Registration");
        adminRegbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminRegbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRegbtnActionPerformed(evt);
            }
        });
        jPanel7.add(adminRegbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 170, 50));

        regMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regMessage.setForeground(new java.awt.Color(255, 0, 0));
        regMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(regMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 320, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 470));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EVENT MANAGEMENT SYSTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 440, 40));

        jPanel8.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 80));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regIdActionPerformed

    private void regPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordActionPerformed

    private void regEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailActionPerformed

    private void logPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logPasswordActionPerformed

    private void customerRegbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRegbtnActionPerformed
        String id = regId.getText();
        String name = regName.getText();
        String email = regEmail.getText();
        String phone = regPhone.getText();
        String type = regType.getText();
        String password = regPassword.getText();
        Customer customer = null;
        if(id.isEmpty() || name.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty()){
            regMessage.setText("Please Fill Up All Field");
            logMessage.setText("");
        }
        else{
            if(type.equals("Local") && type.equals("local")){
                  customer = new LocalCustomer(id, name, phone, email, type, password);
            }
            else if(type.equals("Foreign") && type.equals("foreign")){
                  customer = new ForeignCustomer(id, name, phone, email, type, password);
            }
          
            else{
                customer = new LocalCustomer(id, name, phone, email, type, password);
            }
            customerList.add(customer);
            regMessage.setText("Successfully Customer registered");
            fillRegistrationField();
        }
        
    }//GEN-LAST:event_customerRegbtnActionPerformed

    private void adminRegbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRegbtnActionPerformed
        // TODO add your handling code here:
        
        String id = regId.getText();
        String name = regName.getText();
        String email = regEmail.getText();
        String phone = regPhone.getText();
        String type = regType.getText();
        String password = regPassword.getText();
        
        Admin admin = null;
        
        if(id.isEmpty() || name.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty()){
            regMessage.setText("Please Fill Up All Field");
            logMessage.setText("");
        }
        else{
            
            
                if(type.isEmpty()){
                  admin = new Admin(id, name, email, phone, password);
                }
                else{
                    admin = new Admin(id, name, email, phone, type, password);
                }
            adminList.addAdmin(admin);
            regMessage.setText("Successfully Admin registered");
            fillRegistrationField();
        }
        
        
      
        
    }//GEN-LAST:event_adminRegbtnActionPerformed

    public void fillRegistrationField(){
        regId.setText("");
        regName.setText("");
        regType.setText("");
        regEmail.setText("");
        logMessage.setText("");
        regPhone.setText("");
        regPassword.setText("");
    }
    private void adminLogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInBtnActionPerformed
        // TODO add your handling code here:
        String id = logId.getText();
        String password = logPassword.getText();
        boolean b = adminList.checkPassword(id, password);
        if(b){
            AdminFrame adminFrame = new AdminFrame();
            adminFrame.setVisible(true);
            adminFrame.eventListMaintain = this.eventList;
            this.setVisible(false);
            adminFrame.loginREgistration = this;
            fillLogField();
            fillRegistrationField();
          
        }
        else{
            logMessage.setText("id and password does not match");
            regMessage.setText("");
        }
    }//GEN-LAST:event_adminLogInBtnActionPerformed

    private void customerLogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLogInBtnActionPerformed
        // TODO add your handling code here:
         String id = logId.getText();
        String password = logPassword.getText();
        boolean b = customerList.checkCustomer(id, password);
        if(b){
            CustomerFrame customerFrame = new CustomerFrame();
            customerFrame.setVisible(true);
            customerFrame.eventListMaintain = this.eventList;
            this.setVisible(false);
            customerFrame.loginREgistration = this;
            
            fillLogField();
            fillRegistrationField();
          
        }
        else{
            logMessage.setText("id and password does not match");
            regMessage.setText("");
        }
    }//GEN-LAST:event_customerLogInBtnActionPerformed

    public void fillLogField(){
        logId.setText("");
        logPassword.setText("");
        logMessage.setText("");
        regMessage.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginREgistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginREgistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginREgistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginREgistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginREgistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLogInBtn;
    private javax.swing.JButton adminRegbtn;
    private javax.swing.JButton customerLogInBtn;
    private javax.swing.JButton customerRegbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JTextField logId;
    private javax.swing.JLabel logMessage;
    private javax.swing.JPasswordField logPassword;
    private javax.swing.JTextField regEmail;
    private javax.swing.JTextField regId;
    private javax.swing.JLabel regMessage;
    private javax.swing.JTextField regName;
    private javax.swing.JPasswordField regPassword;
    private javax.swing.JTextField regPhone;
    private javax.swing.JTextField regType;
    // End of variables declaration//GEN-END:variables
}
